# Generated by Django 4.2 on 2023-04-19 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_question_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_questions', to='survey.block'),
        ),
    ]
