# Generated by Django 4.2 on 2023-04-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_question_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
